// <auto-generated />
using System;
using Infrastructure.DatabaseContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(SqliteDbContext))]
    [Migration("20240405142315_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("CommentStudent", b =>
                {
                    b.Property<Guid>("CommentGuid")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LikersGuid")
                        .HasColumnType("TEXT");

                    b.HasKey("CommentGuid", "LikersGuid");

                    b.HasIndex("LikersGuid");

                    b.ToTable("CommentStudent");
                });

            modelBuilder.Entity("Domain.DataModel.Comment", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AuthorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("InResponeseToId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PostId")
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.HasIndex("AuthorId");

                    b.HasIndex("InResponeseToId");

                    b.HasIndex("PostId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("Domain.DataModel.Event", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Fee")
                        .HasColumnType("TEXT");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OrganizerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ViewCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Guid");

                    b.HasIndex("OrganizerId");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("Domain.DataModel.Post", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AuthorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.HasIndex("AuthorId");

                    b.HasIndex("EventId");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("Domain.DataModel.Report", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AuthorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Feedback")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResponderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ResponderId");

                    b.ToTable("Report");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Report");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.DataModel.User", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("SaltedPasswordHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("BLOB")
                        .IsFixedLength();

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.HasIndex("Email");

                    b.HasIndex("Username");

                    b.ToTable("User");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("EventStudent", b =>
                {
                    b.Property<Guid>("InterestedGuid")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SubscribedEventsGuid")
                        .HasColumnType("TEXT");

                    b.HasKey("InterestedGuid", "SubscribedEventsGuid");

                    b.HasIndex("SubscribedEventsGuid");

                    b.ToTable("EventStudent");
                });

            modelBuilder.Entity("EventStudent1", b =>
                {
                    b.Property<Guid>("EventGuid")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ParticipantsGuid")
                        .HasColumnType("TEXT");

                    b.HasKey("EventGuid", "ParticipantsGuid");

                    b.HasIndex("ParticipantsGuid");

                    b.ToTable("EventStudent1");
                });

            modelBuilder.Entity("StudentStudent", b =>
                {
                    b.Property<Guid>("FriendsGuid")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StudentGuid")
                        .HasColumnType("TEXT");

                    b.HasKey("FriendsGuid", "StudentGuid");

                    b.HasIndex("StudentGuid");

                    b.ToTable("StudentStudent");
                });

            modelBuilder.Entity("Domain.DataModel.CommentReport", b =>
                {
                    b.HasBaseType("Domain.DataModel.Report");

                    b.Property<Guid>("ReportedCommentId")
                        .HasColumnType("TEXT");

                    b.HasIndex("ReportedCommentId");

                    b.HasDiscriminator().HasValue("CommentReport");
                });

            modelBuilder.Entity("Domain.DataModel.EventReport", b =>
                {
                    b.HasBaseType("Domain.DataModel.Report");

                    b.Property<Guid>("ReportedEventId")
                        .HasColumnType("TEXT");

                    b.HasIndex("ReportedEventId");

                    b.HasDiscriminator().HasValue("EventReport");
                });

            modelBuilder.Entity("Domain.DataModel.PostReport", b =>
                {
                    b.HasBaseType("Domain.DataModel.Report");

                    b.Property<Guid>("ReportedPostId")
                        .HasColumnType("TEXT");

                    b.HasIndex("ReportedPostId");

                    b.HasDiscriminator().HasValue("PostReport");
                });

            modelBuilder.Entity("Domain.DataModel.Administrator", b =>
                {
                    b.HasBaseType("Domain.DataModel.User");

                    b.HasDiscriminator().HasValue("Administrator");
                });

            modelBuilder.Entity("Domain.DataModel.Student", b =>
                {
                    b.HasBaseType("Domain.DataModel.User");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailNotification")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOrganizer")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("CommentStudent", b =>
                {
                    b.HasOne("Domain.DataModel.Comment", null)
                        .WithMany()
                        .HasForeignKey("CommentGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.DataModel.Student", null)
                        .WithMany()
                        .HasForeignKey("LikersGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.DataModel.Comment", b =>
                {
                    b.HasOne("Domain.DataModel.Student", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.DataModel.Comment", "InResponseTo")
                        .WithMany("Responses")
                        .HasForeignKey("InResponeseToId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.DataModel.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("InResponseTo");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Domain.DataModel.Event", b =>
                {
                    b.HasOne("Domain.DataModel.Student", "Organizer")
                        .WithMany("OrganizedEvents")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("Domain.DataModel.Post", b =>
                {
                    b.HasOne("Domain.DataModel.Student", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.DataModel.Event", "Event")
                        .WithMany("Posts")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Domain.DataModel.Report", b =>
                {
                    b.HasOne("Domain.DataModel.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.DataModel.Administrator", "Responder")
                        .WithMany()
                        .HasForeignKey("ResponderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Author");

                    b.Navigation("Responder");
                });

            modelBuilder.Entity("EventStudent", b =>
                {
                    b.HasOne("Domain.DataModel.Student", null)
                        .WithMany()
                        .HasForeignKey("InterestedGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.DataModel.Event", null)
                        .WithMany()
                        .HasForeignKey("SubscribedEventsGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventStudent1", b =>
                {
                    b.HasOne("Domain.DataModel.Event", null)
                        .WithMany()
                        .HasForeignKey("EventGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.DataModel.Student", null)
                        .WithMany()
                        .HasForeignKey("ParticipantsGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudentStudent", b =>
                {
                    b.HasOne("Domain.DataModel.Student", null)
                        .WithMany()
                        .HasForeignKey("FriendsGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.DataModel.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.DataModel.CommentReport", b =>
                {
                    b.HasOne("Domain.DataModel.Comment", "ReportedComment")
                        .WithMany()
                        .HasForeignKey("ReportedCommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportedComment");
                });

            modelBuilder.Entity("Domain.DataModel.EventReport", b =>
                {
                    b.HasOne("Domain.DataModel.Event", "ReportedEvent")
                        .WithMany()
                        .HasForeignKey("ReportedEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportedEvent");
                });

            modelBuilder.Entity("Domain.DataModel.PostReport", b =>
                {
                    b.HasOne("Domain.DataModel.Post", "ReportedPost")
                        .WithMany()
                        .HasForeignKey("ReportedPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportedPost");
                });

            modelBuilder.Entity("Domain.DataModel.Comment", b =>
                {
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("Domain.DataModel.Event", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Domain.DataModel.Post", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Domain.DataModel.Student", b =>
                {
                    b.Navigation("OrganizedEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
