// <auto-generated />
using System;
using Infrastructure.DatabaseContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(SqliteDbContext))]
    [Migration("20240529191132_AddReactionsAndLikes")]
    partial class AddReactionsAndLikes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("Domain.DataModel.BaseNotification", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Seen")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.ToTable("BaseNotification");

                    b.HasDiscriminator<string>("Discriminator").HasValue("BaseNotification");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.DataModel.Comment", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AuthorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("InResponeseToId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PostId")
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.HasIndex("AuthorId");

                    b.HasIndex("InResponeseToId");

                    b.HasIndex("PostId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("Domain.DataModel.Event", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Fee")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OrganizerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ViewCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Guid");

                    b.HasIndex("OrganizerId");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("Domain.DataModel.Feedback", b =>
                {
                    b.Property<Guid>("AuthorId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AuthorId", "EventId");

                    b.HasIndex("EventId");

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("Domain.DataModel.Like", b =>
                {
                    b.Property<Guid>("AuthorId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CommentId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDislike")
                        .HasColumnType("INTEGER");

                    b.HasKey("AuthorId", "CommentId");

                    b.HasIndex("CommentId");

                    b.ToTable("Like");
                });

            modelBuilder.Entity("Domain.DataModel.Picture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Picture");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Picture");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.DataModel.Post", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AuthorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.HasIndex("AuthorId");

                    b.HasIndex("EventId");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("Domain.DataModel.Reaction", b =>
                {
                    b.Property<Guid>("AuthorId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PostId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.HasKey("AuthorId", "PostId");

                    b.HasIndex("PostId");

                    b.ToTable("Reaction");
                });

            modelBuilder.Entity("Domain.DataModel.Report", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AuthorId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Feedback")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResponderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ResponderId");

                    b.ToTable("Report");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Report");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.DataModel.User", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailNotification")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOrganizer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("EventUser", b =>
                {
                    b.Property<Guid>("InterestedGuid")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SubscribedEventsGuid")
                        .HasColumnType("TEXT");

                    b.HasKey("InterestedGuid", "SubscribedEventsGuid");

                    b.HasIndex("SubscribedEventsGuid");

                    b.ToTable("EventUser");
                });

            modelBuilder.Entity("EventUser1", b =>
                {
                    b.Property<Guid>("JoinedEventsGuid")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ParticipantsGuid")
                        .HasColumnType("TEXT");

                    b.HasKey("JoinedEventsGuid", "ParticipantsGuid");

                    b.HasIndex("ParticipantsGuid");

                    b.ToTable("EventUser1");
                });

            modelBuilder.Entity("UserUser", b =>
                {
                    b.Property<Guid>("FriendsGuid")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("TEXT");

                    b.HasKey("FriendsGuid", "UserGuid");

                    b.HasIndex("UserGuid");

                    b.ToTable("UserUser");
                });

            modelBuilder.Entity("Domain.DataModel.FriendRequest", b =>
                {
                    b.HasBaseType("Domain.DataModel.BaseNotification");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("TEXT");

                    b.HasIndex("AuthorId");

                    b.HasIndex("TargetId");

                    b.HasDiscriminator().HasValue("FriendRequest");
                });

            modelBuilder.Entity("Domain.DataModel.Notification", b =>
                {
                    b.HasBaseType("Domain.DataModel.BaseNotification");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.HasIndex("TargetId");

                    b.HasDiscriminator().HasValue("Notification");
                });

            modelBuilder.Entity("Domain.DataModel.SocialNotification", b =>
                {
                    b.HasBaseType("Domain.DataModel.BaseNotification");

                    b.Property<Guid>("FriendId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.HasIndex("FriendId");

                    b.HasIndex("TargetId");

                    b.ToTable("BaseNotification", t =>
                        {
                            t.Property("Type")
                                .HasColumnName("SocialNotification_Type");
                        });

                    b.HasDiscriminator().HasValue("SocialNotification");
                });

            modelBuilder.Entity("Domain.DataModel.EventPicture", b =>
                {
                    b.HasBaseType("Domain.DataModel.Picture");

                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT");

                    b.HasIndex("EventId");

                    b.HasDiscriminator().HasValue("EventPicture");
                });

            modelBuilder.Entity("Domain.DataModel.PostPicture", b =>
                {
                    b.HasBaseType("Domain.DataModel.Picture");

                    b.Property<Guid>("PostId")
                        .HasColumnType("TEXT");

                    b.HasIndex("PostId");

                    b.HasDiscriminator().HasValue("PostPicture");
                });

            modelBuilder.Entity("Domain.DataModel.CommentReport", b =>
                {
                    b.HasBaseType("Domain.DataModel.Report");

                    b.Property<Guid>("ReportedCommentId")
                        .HasColumnType("TEXT");

                    b.HasIndex("ReportedCommentId");

                    b.HasDiscriminator().HasValue("CommentReport");
                });

            modelBuilder.Entity("Domain.DataModel.EventReport", b =>
                {
                    b.HasBaseType("Domain.DataModel.Report");

                    b.Property<Guid>("ReportedEventId")
                        .HasColumnType("TEXT");

                    b.HasIndex("ReportedEventId");

                    b.HasDiscriminator().HasValue("EventReport");
                });

            modelBuilder.Entity("Domain.DataModel.PostReport", b =>
                {
                    b.HasBaseType("Domain.DataModel.Report");

                    b.Property<Guid>("ReportedPostId")
                        .HasColumnType("TEXT");

                    b.HasIndex("ReportedPostId");

                    b.HasDiscriminator().HasValue("PostReport");
                });

            modelBuilder.Entity("Domain.DataModel.Comment", b =>
                {
                    b.HasOne("Domain.DataModel.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.DataModel.Comment", "InResponseTo")
                        .WithMany("Responses")
                        .HasForeignKey("InResponeseToId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.DataModel.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("InResponseTo");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Domain.DataModel.Event", b =>
                {
                    b.HasOne("Domain.DataModel.User", "Organizer")
                        .WithMany("OrganizedEvents")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("Domain.DataModel.Feedback", b =>
                {
                    b.HasOne("Domain.DataModel.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.DataModel.Event", "Event")
                        .WithMany("Feedback")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Domain.DataModel.Like", b =>
                {
                    b.HasOne("Domain.DataModel.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.DataModel.Comment", "Comment")
                        .WithMany("Likes")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Comment");
                });

            modelBuilder.Entity("Domain.DataModel.Post", b =>
                {
                    b.HasOne("Domain.DataModel.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.DataModel.Event", "Event")
                        .WithMany("Posts")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Domain.DataModel.Reaction", b =>
                {
                    b.HasOne("Domain.DataModel.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.DataModel.Post", "Post")
                        .WithMany("Reactions")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Domain.DataModel.Report", b =>
                {
                    b.HasOne("Domain.DataModel.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.DataModel.User", "Responder")
                        .WithMany()
                        .HasForeignKey("ResponderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Author");

                    b.Navigation("Responder");
                });

            modelBuilder.Entity("EventUser", b =>
                {
                    b.HasOne("Domain.DataModel.User", null)
                        .WithMany()
                        .HasForeignKey("InterestedGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.DataModel.Event", null)
                        .WithMany()
                        .HasForeignKey("SubscribedEventsGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventUser1", b =>
                {
                    b.HasOne("Domain.DataModel.Event", null)
                        .WithMany()
                        .HasForeignKey("JoinedEventsGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.DataModel.User", null)
                        .WithMany()
                        .HasForeignKey("ParticipantsGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserUser", b =>
                {
                    b.HasOne("Domain.DataModel.User", null)
                        .WithMany()
                        .HasForeignKey("FriendsGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.DataModel.User", null)
                        .WithMany()
                        .HasForeignKey("UserGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.DataModel.FriendRequest", b =>
                {
                    b.HasOne("Domain.DataModel.User", "Author")
                        .WithMany("SentFriendRequests")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.DataModel.User", "Target")
                        .WithMany("ReceivedFriendRequests")
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("Domain.DataModel.Notification", b =>
                {
                    b.HasOne("Domain.DataModel.User", "Target")
                        .WithMany("PersonalNotifications")
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Target");
                });

            modelBuilder.Entity("Domain.DataModel.SocialNotification", b =>
                {
                    b.HasOne("Domain.DataModel.User", "Friend")
                        .WithMany()
                        .HasForeignKey("FriendId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.DataModel.User", "Target")
                        .WithMany("SocialNotifications")
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Friend");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("Domain.DataModel.EventPicture", b =>
                {
                    b.HasOne("Domain.DataModel.Event", "Event")
                        .WithMany("Pictures")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Domain.DataModel.PostPicture", b =>
                {
                    b.HasOne("Domain.DataModel.Post", "Post")
                        .WithMany("Pictures")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Domain.DataModel.CommentReport", b =>
                {
                    b.HasOne("Domain.DataModel.Comment", "ReportedComment")
                        .WithMany()
                        .HasForeignKey("ReportedCommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportedComment");
                });

            modelBuilder.Entity("Domain.DataModel.EventReport", b =>
                {
                    b.HasOne("Domain.DataModel.Event", "ReportedEvent")
                        .WithMany()
                        .HasForeignKey("ReportedEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportedEvent");
                });

            modelBuilder.Entity("Domain.DataModel.PostReport", b =>
                {
                    b.HasOne("Domain.DataModel.Post", "ReportedPost")
                        .WithMany()
                        .HasForeignKey("ReportedPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportedPost");
                });

            modelBuilder.Entity("Domain.DataModel.Comment", b =>
                {
                    b.Navigation("Likes");

                    b.Navigation("Responses");
                });

            modelBuilder.Entity("Domain.DataModel.Event", b =>
                {
                    b.Navigation("Feedback");

                    b.Navigation("Pictures");

                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Domain.DataModel.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Pictures");

                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("Domain.DataModel.User", b =>
                {
                    b.Navigation("OrganizedEvents");

                    b.Navigation("PersonalNotifications");

                    b.Navigation("ReceivedFriendRequests");

                    b.Navigation("SentFriendRequests");

                    b.Navigation("SocialNotifications");
                });
#pragma warning restore 612, 618
        }
    }
}
