on:
  pull_request:
      branches: [ "main", "dev" ]

env:
  DOTNET_VERSION: '8.0.X'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }} 

    - name: Build and test
      run: |
        dotnet restore
        dotnet build --configuration Release
        dotnet test -c Release
    
